server:
  port: 9527
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka.7001.com:7001/eureka
  instance:
    hostname: cloud-gateway-service

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb:http://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
            #- After=2023-08-18T10:21:29.857+08:00[Asia/Shanghai]
            #- Before=2023-08-18T10:21:29.857+08:00[Asia/Shanghai]
           # - Between=2023-08-18T10:23:29.857+08:00[Asia/Shanghai],2023-08-18T10:25:29.857+08:00[Asia/Shanghai]
           # - Cookie=username,tom
            #- Header=X-Request-Id,\d+
           # - Host=**.atlily.com
           # - Method=GET
           # - Query=username,\d+
        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb:http://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由




